name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # Add a new job to run your tests with access to appsettings.json
  test:

    runs-on: ubuntu-latest

    needs: build  # Wait for the 'build' job to complete first

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Copy appsettings.json
      run: cp NewRevolutionaryBank.Web/appsettings.json NewRevolutionaryBank.Tests.Services/

    - name: Restore dependencies
      run: dotnet restore NewRevolutionaryBank.Tests.Services

    - name: Test
      run: dotnet test --no-build --verbosity normal NewRevolutionaryBank.Tests.Services
